platform :ios, '10.0'

target 'RocketRides' do
  use_frameworks!

  pod 'Alamofire', '~> 4'
  pod 'Stripe'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = %x[uname -m].strip
  end
end
